version: "3.9"

services:
  web:
    container_name: todo_api_web
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    build: .
    ports:
      - "8080:8080"
    command: honcho start
    volumes:
      - .:/todo

    environment:
      DJANGO_SETTINGS_MODULE: "todo.settings"
      DEBUG: 1
      SECRET_KEY: django-insecure-x@(-n!hl89*_5@a&ug*2spzrwbc1rh=om_f8l=d@k8$mk1@fn5
      REDIS_URL: redis://redis
      DB_HOST: postgres
      POSTGRES_DB: "todo_api_dev"
      POSTGRES_USER: "todo_api_dev"
      POSTGRES_PASSWORD: "pass"

  redis:
    container_name: todo_api_redis
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  postgres:
    container_name: postgres_container
    image: postgres:13.8
    environment:
      POSTGRES_DB: "todo_api_dev"
      POSTGRES_USER: "todo_api_dev"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_api_dev -d todo_api_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  pgadmin:
    depends_on:
      postgres:
        condition: service_healthy
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: "todo_api_dev@example.com"
      PGADMIN_DEFAULT_PASSWORD: "todo_api_dev"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  celery:
    depends_on:
      redis:
        condition: service_healthy
    container_name: celery_container
    restart: always
    build: .
    command: celery -A todo worker -l info
    volumes:
      - .:/todo
    environment:
      DEBUG: 1
      SECRET_KEY: django-insecure-x@(-n!hl89*_5@a&ug*2spzrwbc1rh=om_f8l=d@k8$mk1@fn5


volumes:
  postgres_data: